/**
 * A single memory entry stored by an agent.
 * @property > id:string - Unique identifier for this entry.
 * @property > agentId:string - ID of the agent that owns this memory.
 * @property > content: unkown - The actual content of the memory.
 * @property > metadata: Record<string, unknown> - Optional metadata for filtering and organization.
 * @property > createdAt: Date - When this entry was created.
 * @property > updatedAt: Date - When this entry was last updated.
 * @property > embedding: number[] - Optional vector embedding for semantic search.
 */
export interface MemoryEntry {
    readonly id: string;
    readonly agentId: string;
    readonly content: unknown;
    readonly metadata?: Record<string, unknown>;
    readonly createdAt: Date;
    readonly updatedAt?: Date;
    readonly embedding?: number[];
}

/**
 * Options for writing a memory entry.
 * 
 * @property > namespace:string - Namespace or partition for the memory.
 * @property > ttl:number - Time-to-live in seconds.
 * @property > id:string - Custom ID (otherwise auto-generated by the adapter).
 */
export interface MemoryWriteOptions {
    namespace?: string;
    ttl?: number;
    id?: string;
}

/**
 * Options for reading memory entries.
 * 
 * @property > namespace:string - Filter by namespace.
 * @property > limit:number - Maximum number of entries to return.
 * @property > offset:number - Offset for simple pagination.
 * @property > cursor:string - Cursor for token-based pagination (ideal for REST APIs).
 * @property > filter:Record<string, unknown> - Filter by metadata (key-value matches).
 * @property > orderBy:'createdAt' | 'updatedAt' - Sort order field.
 * @property > orderDirection:'asc' | 'desc' - Sort direction.
 */
export interface MemoryReadOptions {
    namespace?: string;
    limit?: number;
    offset?: number;
    cursor?: string;
    filter?: Record<string, unknown>;
    orderBy?: 'createdAt' | 'updatedAt';
    orderDirection?: 'asc' | 'desc';
}

/**
 * Result of a memory read operation.
 * 
 * @property > entries:MemoryEntry[] - The retrieved memory entries.
 * @property > nextCursor:string - Optional cursor to retrieve the next page of results.
 */
export interface MemoryReadResult {
    entries: MemoryEntry[];
    nextCursor?: string;
}

/**
 * Options for semantic search.
 * 
 * @property > topK:number - Number of results to return.
 * @property > minScore:number - Minimum similarity score (0 to 1).
 */
export interface MemorySearchOptions extends Omit<MemoryReadOptions, 'cursor' | 'offset'> {
    topK?: number;
    minScore?: number;
}

/**
 * Result of a memory search operation.
 * 
 * @property > entries:MemoryEntry[] - The retrieved memory entries.
 * @property > scores:number[] - Similarity scores for the entries (if available).
 */
export interface MemorySearchResult {
    entries: MemoryEntry[];
    scores?: number[];
}
