'use client';

import { openai } from '@ai-sdk/openai';
import type { UIToolInvocation } from 'ai';

export default function OpenAIImageGenerationView({
  invocation
}: {
  invocation: UIToolInvocation<ReturnType<typeof openai.tools.imageGeneration>>;
}) {
  switch (invocation.state) {
    case 'input-streaming':
    case 'input-available':
      return <div>Generating image…</div>;

    case 'output-available':
      return (
        <img
          src={`data:image/png;base64,${invocation.output.result}`}
          alt="Generated by OpenAI image tool"
          style={{ maxWidth: '100%', borderRadius: 8 }}
        />
      );

    case 'output-error':
      return <div>Image generation failed.</div>;

    case 'output-denied':
      return <div>Image generation was denied.</div>;
    default:
      return null;
  }
}
