import './globals.css';
import { Inter } from 'next/font/google';
import Toaster from './toaster';
import { KasadaClient } from '@/kasada/kasada-client';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster />
      <KasadaClient />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
