/**
 * Redirect order and first-match behavior are a public compatibility contract.
 * Keep this list aligned with the effective production declarations.
 */
type LegacyRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

type LegacyRedirectTuple = readonly [
  source: string,
  destination: string,
  permanent: boolean,
];

const legacyRedirectData = [
  ['/docs/guides/rag-chatbot', '/cookbook/guides/rag-chatbot', true],
  [
    '/docs/guides/multi-modal-chatbot',
    '/cookbook/guides/multi-modal-chatbot',
    true,
  ],
  ['/docs/guides/slackbot', '/cookbook/guides/slackbot', true],
  [
    '/docs/guides/natural-language-postgres',
    '/cookbook/guides/natural-language-postgres',
    true,
  ],
  ['/docs/guides/computer-use', '/cookbook/guides/computer-use', true],
  ['/docs/guides/claude-4', '/cookbook/guides/claude-4', true],
  ['/docs/guides/openai-responses', '/cookbook/guides/openai-responses', true],
  ['/docs/guides/sonnet-3-7', '/cookbook/guides/sonnet-3-7', true],
  ['/docs/guides/llama-3_1', '/cookbook/guides/llama-3_1', true],
  ['/docs/guides/gpt-4-5', '/cookbook/guides/gpt-4-5', true],
  ['/docs/guides/o1', '/cookbook/guides/o1', true],
  ['/docs/guides/o3', '/cookbook/guides/o3', true],
  ['/docs/guides/r1', '/cookbook/guides/r1', true],
  ['/docs/guides', '/cookbook/guides', true],
  ['/docs/guides/nextjs-app', '/docs/guides/frameworks/nextjs-app', false],
  ['/docs/guides/nextjs-pages', '/docs/guides/frameworks/nextjs-pages', false],
  ['/docs/guides/sveltekit', '/docs/guides/frameworks/sveltekit', false],
  ['/docs/guides/solidjs', '/docs/getting-started', false],
  [
    '/docs/guides/frameworks/nextjs-app',
    '/docs/getting-started/nextjs-app-router',
    false,
  ],
  [
    '/docs/guides/frameworks/nextjs-pages',
    '/docs/getting-started/nextjs-pages-router',
    false,
  ],
  ['/docs/guides/frameworks/sveltekit', '/docs/getting-started/svelte', false],
  ['/docs/providers', '/providers', true],
  ['/docs/guides/anthropic', '/providers/ai-sdk-providers/anthropic', false],
  ['/docs/guides/cohere', '/providers/ai-sdk-providers/cohere', false],
  [
    '/docs/guides/huggingface',
    '/providers/ai-sdk-providers/huggingface',
    false,
  ],
  ['/docs/guides/langchain', '/providers/ai-sdk-providers/langchain', false],
  ['/docs/guides/openai', '/providers/ai-sdk-providers/openai', false],
  ['/docs/guides/fireworks', '/providers/ai-sdk-providers/fireworks', false],
  ['/docs/guides/mistral', '/providers/ai-sdk-providers/mistral', false],
  [
    '/docs/guides/providers/cohere',
    '/providers/legacy-providers/cohere',
    false,
  ],
  [
    '/docs/guides/providers/langchain',
    '/providers/legacy-providers/langchain',
    false,
  ],
  [
    '/docs/guides/providers/fireworks',
    '/providers/legacy-providers/fireworks',
    false,
  ],
  [
    '/docs/guides/providers/aws-bedrock',
    '/providers/legacy-providers/aws-bedrock',
    false,
  ],
  [
    '/docs/guides/providers/azure-openai',
    '/providers/legacy-providers/azure-openai',
    false,
  ],
  [
    '/docs/guides/providers/google',
    '/providers/legacy-providers/google',
    false,
  ],
  [
    '/docs/guides/providers/inkeep',
    '/providers/legacy-providers/inkeep',
    false,
  ],
  [
    '/docs/guides/providers/mistral',
    '/providers/legacy-providers/mistral',
    false,
  ],
  [
    '/docs/guides/providers/perplexity',
    '/providers/legacy-providers/perplexity',
    false,
  ],
  [
    '/docs/guides/providers/replicate',
    '/providers/legacy-providers/replicate',
    false,
  ],
  [
    '/docs/guides/providers/anthropic',
    '/providers/ai-sdk-providers/anthropic',
    false,
  ],
  [
    '/docs/guides/providers/huggingface',
    '/providers/ai-sdk-providers/huggingface',
    false,
  ],
  [
    '/docs/guides/providers/openai',
    '/providers/ai-sdk-providers/openai',
    false,
  ],
  ['/demo', 'https://chat.vercel.ai', true],
  ['/docs', '/docs/introduction', true],
  ['/docs/ai-sdk-rsc/generative-ui', '/docs/ai-sdk-rsc/overview', true],
  ['/providers', '/providers/ai-sdk-providers', true],
  ['/docs/ai-core', '/docs/ai-sdk-core', true],
  ['/docs/ai-core/generate-text', '/docs/ai-sdk-core/generate-text', true],
  ['/docs/ai-core/generate-object', '/docs/ai-sdk-core/generate-object', true],
  ['/docs/ai-core/stream-text', '/docs/ai-sdk-core/stream-text', true],
  ['/docs/ai-core/stream-object', '/docs/ai-sdk-core/stream-object', true],
  ['/docs/ai-core/prompt', '/docs/ai-sdk-core/prompts', true],
  ['/docs/ai-core/settings', '/docs/ai-sdk-core/settings', true],
  ['/docs/ai-core/tools', '/docs/ai-sdk-core/tools-and-tool-calling', true],
  [
    '/docs/ai-core/custom-provider',
    '/providers/community-providers/custom-providers',
    true,
  ],
  [
    '/providers/community-providers/index.mjs',
    '/providers/community-providers',
    true,
  ],
  ['/api/completion', '/docs/ai-sdk-ui/completion', true],
  ['/docs/ai-core/anthropic', '/providers/ai-sdk-providers/anthropic', true],
  ['/docs/ai-core/openai', '/providers/ai-sdk-providers/openai', true],
  ['/docs/ai-core/mistral', '/providers/ai-sdk-providers/mistral', true],
  ['/docs/ai-core/google', '/providers/ai-sdk-providers/google', true],
  ['/docs/concepts', '/docs/advanced', true],
  ['/docs/concepts/ai-rsc', '/docs/ai-sdk-rsc', true],
  [
    '/docs/concepts/backpressure-and-cancellation',
    '/docs/advanced/backpressure',
    true,
  ],
  ['/docs/concepts/caching', '/docs/advanced/caching', true],
  [
    '/docs/concepts/prompt-engineering',
    '/docs/advanced/prompt-engineering',
    true,
  ],
  ['/docs/concepts/streaming', '/docs/advanced/why-streaming', true],
  ['/docs/concepts/tools', '/docs/ai-sdk-core/tools-and-tool-calling', true],
  ['/docs/api-reference', '/docs/reference', true],
  ['/docs/api-reference/use-chat', '/docs/reference/ai-sdk-ui/use-chat', true],
  [
    '/docs/api-reference/use-completion',
    '/docs/reference/ai-sdk-ui/use-completion',
    true,
  ],
  [
    '/docs/api-reference/use-assistant',
    '/docs/reference/ai-sdk-ui/use-assistant',
    true,
  ],
  [
    '/docs/api-reference/ai-stream',
    '/docs/reference/stream-helpers/ai-stream',
    true,
  ],
  [
    '/docs/api-reference/streaming-text-response',
    '/docs/reference/stream-helpers/streaming-text-response',
    true,
  ],
  [
    '/docs/api-reference/streaming-react-response',
    '/docs/reference/stream-helpers/streaming-react-response',
    true,
  ],
  [
    '/docs/api-reference/stream-to-response',
    '/docs/reference/stream-helpers/stream-to-response',
    true,
  ],
  [
    '/docs/api-reference/stream-data',
    '/docs/reference/stream-helpers/stream-data',
    true,
  ],
  ['/docs/api-reference/providers', '/docs/providers/ai-sdk-providers', true],
  [
    '/docs/api-reference/providers/anthropic-stream',
    '/docs/reference/stream-helpers/anthropic-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/assistant-response',
    '/docs/reference/stream-helpers/assistant-response',
    true,
  ],
  [
    '/docs/api-reference/providers/aws-bedrock-stream',
    '/docs/reference/stream-helpers/aws-bedrock-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/cohere-stream',
    '/docs/reference/stream-helpers/cohere-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/google-generative-ai-stream',
    '/docs/reference/stream-helpers/google-generative-ai-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/huggingface-stream',
    '/docs/reference/stream-helpers/huggingface-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/inkeep-stream',
    '/docs/reference/stream-helpers/inkeep-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/langchain-stream',
    '/docs/reference/stream-helpers/langchain-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/mistral-stream',
    '/docs/reference/stream-helpers/mistral-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/openai-stream',
    '/docs/reference/stream-helpers/openai-stream',
    true,
  ],
  [
    '/docs/api-reference/providers/replicate-stream',
    '/docs/reference/stream-helpers/replicate-stream',
    true,
  ],
  ['/docs/api-reference/generative-ui', '/docs/reference/ai-sdk-rsc', true],
  [
    '/docs/api-reference/generative-ui/create-ai',
    '/docs/reference/ai-sdk-rsc/create-ai',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/create-streamable-ui',
    '/docs/reference/ai-sdk-rsc/create-streamable-ui',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/create-streamable-value',
    '/docs/reference/ai-sdk-rsc/create-streamable-value',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/get-ai-state',
    '/docs/reference/ai-sdk-rsc/get-ai-state',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/get-mutable-ai-state',
    '/docs/reference/ai-sdk-rsc/get-mutable-ai-state',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/render',
    '/docs/reference/ai-sdk-rsc/stream-ui',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/use-actions',
    '/docs/reference/ai-sdk-rsc/use-actions',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/use-ai-state',
    '/docs/reference/ai-sdk-rsc/use-ai-state',
    true,
  ],
  [
    '/docs/api-reference/generative-ui/use-ui-state',
    '/docs/reference/ai-sdk-rsc/use-ui-state',
    true,
  ],
  [
    '/docs/ai-sdk-core/schemas-and-zod',
    '/docs/foundations/tools#schema-specification-and-validation-with-zod',
    true,
  ],
  [
    '/docs/ai-sdk-core/providers-and-models',
    '/docs/foundations/providers-and-models',
    true,
  ],
  ['/docs/advanced/why-streaming', '/docs/foundations/streaming', true],
  [
    '/docs/reference/stream-helpers/lang-chain-stream',
    '/docs/reference/stream-helpers/langchain-stream',
    true,
  ],
  [
    '/docs/reference/stream-helpers/assistant-response',
    '/docs/reference/ai-sdk-ui/assistant-response',
    true,
  ],
  [
    '/docs/reference/stream-helpers/streaming-react-response',
    '/docs/troubleshooting/migration-guide/migration-guide-3-2#removed-functionality',
    true,
  ],
  [
    '/docs/reference/stream-helpers/open-ai-stream',
    '/docs/reference/stream-helpers/openai-stream',
    true,
  ],
  [
    '/docs/ai-sdk-rsc/streaming-user-interfaces',
    '/docs/ai-sdk-rsc/streaming-react-components',
    true,
  ],
  ['/reference', '/docs/reference', true],
  [
    '/docs/getting-started/new-docs/building-applications',
    '/docs/getting-started',
    true,
  ],
  ['/docs/foundations/tools-and-tool-calling', '/docs/foundations/tools', true],
  [
    '/docs/ai-sdk-core/generate-object',
    '/docs/ai-sdk-core/generating-structured-data',
    true,
  ],
  [
    '/docs/reference/ai-sdk-core/generate-object',
    '/docs/reference/ai-sdk-core/output',
    true,
  ],
  [
    '/docs/reference/ai-sdk-core/stream-object',
    '/docs/reference/ai-sdk-core/output',
    true,
  ],
  [
    '/docs/examples/next-app/tools/call-function',
    '/examples/next-app/tools/call-tool',
    true,
  ],
  [
    '/docs/ai-sdk-rsc/ai-ui-states',
    '/docs/ai-sdk-rsc/generative-ui-state',
    true,
  ],
  [
    '/docs/ai-sdk-core/model-management',
    '/docs/ai-sdk-core/provider-management',
    true,
  ],
  [
    '/docs/examples/next-pages/basics/stream-text-generation',
    '/examples/next-pages/basics/streaming-text-generation',
    true,
  ],
  ['/docs/api-reference/prompts', '/docs/foundations/prompts', true],
  ['/docs/ai-sdk-core/stream-text', '/docs/ai-sdk-core/generating-text', true],
  [
    '/docs/examples/next-pages/basics/generate-text',
    '/examples/next-pages/basics/generating-text',
    true,
  ],
  [
    '/docs/reference/stream-helpers/huggingface-stream',
    '/docs/reference/stream-helpers/hugging-face-stream',
    true,
  ],
  [
    '/docs/fundamentals/providers-and-models',
    '/docs/foundations/providers-and-models',
    true,
  ],
  ['/docs/fundamentals/tools', '/docs/foundations/tools', true],
  ['/docs/fundamentals/overview', '/docs/foundations/overview', true],
  ['/docs/fundamentals/prompts', '/docs/foundations/prompts', true],
  ['/docs/fundamentals/streaming', '/docs/foundations/streaming', true],
  [
    '/docs/01.5-fundamentals/providers-and-models',
    '/docs/foundations/providers-and-models',
    true,
  ],
  ['/docs/01.5-fundamentals/tools', '/docs/foundations/tools', true],
  ['/docs/01.5-fundamentals/overview', '/docs/foundations/overview', true],
  ['/docs/01.5-fundamentals/prompts', '/docs/foundations/prompts', true],
  ['/docs/01.5-fundamentals/streaming', '/docs/foundations/streaming', true],
  ['/docs/fundamentals', '/docs/foundations', true],
  ['/docs/01.5-fundamentals', '/docs/foundations', true],
  [
    '/docs/building-your-application/ai-rsc/ai-ui-states',
    '/docs/ai-sdk-rsc/generative-ui-state',
    true,
  ],
  [
    '/ai-sdk-core/tools-and-tool-calling',
    '/docs/ai-sdk-core/tools-and-tool-calling',
    true,
  ],
  [
    '/docs/working-with-llms',
    '/docs/foundations/overview#large-language-models',
    true,
  ],
  [
    '/docs/reference/stream-helpers/awsbedrock-messages-stream',
    '/docs/reference/stream-helpers/aws-bedrock-messages-stream',
    true,
  ],
  [
    '/docs/ai-sdk-core/generate-text',
    '/docs/ai-sdk-core/generating-text',
    true,
  ],
  [
    '/docs/getting-started/docs/building-applications',
    '/docs/getting-started',
    true,
  ],
  ['/docs/api-reference/tokens', '/docs/ai-sdk-core/settings', true],
  ['/docs/ai-sdk/providers/openai', '/providers/ai-sdk-providers/openai', true],
  [
    '/docs/examples/node/basics/stream-chat-completion',
    '/examples/node/generating-text/stream-text-with-chat-prompt',
    true,
  ],
  [
    '/docs/reference/stream-helpers/awsbedrock-stream',
    '/docs/reference/stream-helpers/aws-bedrock-stream',
    true,
  ],
  [
    '/docs/reference/stream-helpers/awsbedrock-llama2-stream',
    '/docs/reference/stream-helpers/aws-bedrock-llama-2-stream',
    true,
  ],
  [
    '/docs/guides/providers/hugging-face',
    '/docs/reference/stream-helpers/hugging-face-stream',
    true,
  ],
  [
    '/providers/legacy-providers/hugging-face',
    '/docs/reference/stream-helpers/hugging-face-stream',
    true,
  ],
  ['/docs/db/schema/embeddings', '/docs/ai-sdk-core/embeddings', true],
  ['/docs/ai/embedding', '/docs/ai-sdk-core/embeddings', true],
  ['/docs/acknowledgements', '/docs/introduction', true],
  ['/docs/guides/frameworks/solidjs', '/docs/getting-started', true],
  [
    '/providers/legacy-providers/fireworks',
    '/providers/ai-sdk-providers/fireworks',
    true,
  ],
  [
    '/providers/legacy-providers/fireworks-ai',
    '/providers/ai-sdk-providers/fireworks',
    true,
  ],
  [
    '/docs/troubleshooting/streaming-not-working-in-production',
    '/docs/troubleshooting/streaming-not-working-on-vercel',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/azure-stream-slow',
    '/docs/troubleshooting/azure-stream-slow',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/client-side-function-calls-not-invoked',
    '/docs/troubleshooting/client-side-function-calls-not-invoked',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/server-actions-in-client-components',
    '/docs/troubleshooting/server-actions-in-client-components',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/strange-stream-output',
    '/docs/troubleshooting/strange-stream-output',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/streamable-ui-errors',
    '/docs/troubleshooting/streamable-ui-errors',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/streaming-not-working-on-vercel',
    '/docs/troubleshooting/streaming-not-working-on-vercel',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/streaming-not-working-on-vercel-pages-router',
    '/docs/troubleshooting/streaming-not-working-on-vercel-pages-router',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/timeout-on-vercel',
    '/docs/troubleshooting/timeout-on-vercel',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/unclosed-streams',
    '/docs/troubleshooting/unclosed-streams',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/use-chat-failed-to-parse-stream',
    '/docs/troubleshooting/use-chat-failed-to-parse-stream',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/client-stream-error',
    '/docs/troubleshooting/client-stream-error',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/use-chat-tools-no-response',
    '/docs/troubleshooting/use-chat-tools-no-response',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/nan-token-counts-openai-streaming',
    '/docs/troubleshooting/nan-token-counts-openai-streaming',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/model-is-not-assignable-to-type',
    '/docs/troubleshooting/model-is-not-assignable-to-type',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/typescript-cannot-find-namespace-jsx',
    '/docs/troubleshooting/typescript-cannot-find-namespace-jsx',
    true,
  ],
  [
    '/docs/troubleshooting/common-issues/react-maximum-update-depth-exceeded',
    '/docs/troubleshooting/react-maximum-update-depth-exceeded',
    true,
  ],
  [
    '/docs/reference/stream-helpers/inkeeps-stream',
    '/docs/reference/stream-helpers/inkeep-stream',
    true,
  ],
  [
    '/docs/ai-sdk-core/stream-object',
    '/docs/ai-sdk-core/generating-structured-data',
    true,
  ],
  [
    '/docs/ai-sdk-core/ai-sdk-core/generating-structured-data',
    '/docs/ai-sdk-core/generating-structured-data',
    true,
  ],
  ['/docs/ai-rsc', '/docs/ai-sdk-rsc', true],
  ['/providers/langchain', '/providers/adapters/langchain', true],
  [
    '/getting-started/nextjs-app-router',
    '/docs/getting-started/nextjs-app-router',
    true,
  ],
  ['/docs/working-with-llms/settings', '/docs/ai-sdk-core/settings', true],
  [
    '/docs/reference/ai-sdk-core/model-registry',
    '/docs/reference/ai-sdk-core/provider-registry',
    true,
  ],
  ['/docs/providers/ai-sdk-providers', '/providers/ai-sdk-providers', true],
  ['/docs/examples/sveltekit/chat/stream-chat-completion', '/examples', true],
  [
    '/docs/examples/node/basics/stream-text-generation',
    '/examples/node/generating-text/stream-text',
    true,
  ],
  [
    '/docs/examples/node/basics/generate-text',
    '/examples/node/generating-text/generate-text',
    true,
  ],
  [
    '/docs/examples/next-app/tools/render-component-during-call',
    '/examples/next-app/tools/render-interface-during-tool-call',
    true,
  ],
  [
    '/docs/examples/next-app/state-management/persist-and-restore-states',
    '/examples/next-app/state-management/save-and-restore-states',
    true,
  ],
  [
    '/docs/examples/next-app/state-management/ai-and-ui-states',
    '/examples/next-app/state-management/ai-ui-states',
    true,
  ],
  [
    '/docs/examples/next-app/interface/stream-component-updates',
    '/examples/next-app/interface/stream-component-updates',
    true,
  ],
  [
    '/docs/examples/next-app/interface/route-components',
    '/examples/next-app/interface/route-components',
    true,
  ],
  [
    '/docs/examples/next-app/interface/add-interactions-to-context',
    '/examples/next-app/interface',
    true,
  ],
  [
    '/docs/examples/next-app/basics/stream-text-generation',
    '/examples/next-app/basics/streaming-text-generation',
    true,
  ],
  [
    '/docs/examples/next-app/basics/generate-text',
    '/examples/next-app/basics/generating-text',
    true,
  ],
  [
    '/docs/examples/next-app/basics/generate-object',
    '/examples/next-app/basics/generating-object',
    true,
  ],
  ['/docs/building-your-application/ai-rsc', '/docs/ai-sdk-rsc/overview', true],
  [
    '/docs/ai-sdk-rsc/multi-step-interfaces',
    '/docs/advanced/multistep-interfaces',
    true,
  ],
  ['/docs/ai-sdk-core/ai-sdk-rsc', '/docs/ai-sdk-rsc', true],
  [
    '/docs/ai-sdk-core/ai-sdk-core/settings',
    '/docs/ai-sdk-core/settings',
    true,
  ],
  [
    '/docs/ai-sdk-core/ai-sdk-core/schemas-and-zod',
    '/docs/foundations/tools#schema-specification-and-validation-with-zod',
    true,
  ],
  [
    '/docs/ai-sdk-core/ai-sdk-core/embeddings',
    '/docs/ai-sdk-core/embeddings',
    true,
  ],
  [
    '/docs/ai-sdk-core/ai-sdk-core/generating-text',
    '/docs/ai-sdk-core/generating-text',
    true,
  ],
  ['/docs/ai-sdk-core/ai-sdk-core/prompts', '/docs/foundations/prompts', true],
  ['/docs/advanced/streaming', '/docs/foundations/streaming', true],
  [
    '/providers/openai-compatible-providers/fireworks',
    '/providers/ai-sdk-providers/fireworks',
    true,
  ],
  [
    '/providers/openai-compatible-providers/togetherai',
    '/providers/ai-sdk-providers/togetherai',
    true,
  ],
  [
    '/providers/openai-compatible-providers/baseten',
    '/providers/ai-sdk-providers/baseten',
    true,
  ],
  [
    '/docs/troubleshooting/migration-guide/migration-guide-3-1',
    '/docs/migration-guides/migration-guide-3-1',
    false,
  ],
  [
    '/docs/troubleshooting/migration-guide/migration-guide-3-2',
    '/docs/migration-guides/migration-guide-3-2',
    false,
  ],
  [
    '/docs/troubleshooting/migration-guide/migration-guide-3-3',
    '/docs/migration-guides/migration-guide-3-3',
    false,
  ],
  [
    '/docs/troubleshooting/migration-guide/migration-guide-3-4',
    '/docs/migration-guides/migration-guide-3-4',
    false,
  ],
  [
    '/docs/troubleshooting/migration-guide/migration-guide-4-0',
    '/docs/migration-guides/migration-guide-4-0',
    false,
  ],
  [
    '/docs/ai-sdk-ui/storing-messages',
    '/docs/ai-sdk-ui/chatbot-message-persistence',
    false,
  ],
  [
    '/cookbook/next/restore-messages-from-database',
    '/docs/ai-sdk-ui/chatbot-message-persistence',
    false,
  ],
  [
    '/cookbook/next/save-messages-from-database',
    '/docs/ai-sdk-ui/chatbot-message-persistence',
    false,
  ],
  [
    '/cookbook/next/save-messages-to-database',
    '/docs/ai-sdk-ui/chatbot-message-persistence',
    false,
  ],
  [
    '/docs/ai-sdk-ui/chatbot-with-tool-calling',
    '/docs/ai-sdk-ui/chatbot-tool-usage',
    false,
  ],
  ['/api/notifications', '/', true],
  ['/api/object', '/docs/reference/ai-sdk-ui/use-object', true],
  ['/api/use-chat', '/docs/reference/ai-sdk-ui/use-chat#usechat', true],
  ['/api/use-object', '/docs/reference/ai-sdk-ui/use-object', true],
  ['/docs/ai-sdk-rsc/ErrorBoundary', '/docs/ai-sdk-rsc/error-handling', true],
  [
    '/docs/ai-sdk-ui/api/notifications/schema',
    '/docs/ai-sdk-ui/overview',
    true,
  ],
  [
    '/docs/api-reference/anthropic-stream',
    '/docs/reference/stream-helpers/anthropic-stream',
    true,
  ],
  [
    '/docs/api-reference/assistant-response',
    '/docs/reference/ai-sdk-ui/assistant-response',
    true,
  ],
  [
    '/docs/api-reference/huggingface-stream',
    '/docs/reference/stream-helpers/hugging-face-stream',
    true,
  ],
  [
    '/docs/api-reference/langchain-stream',
    '/docs/reference/stream-helpers/langchain-stream',
    true,
  ],
  [
    '/docs/api-reference/openai-stream',
    '/docs/reference/stream-helpers/openai-stream',
    true,
  ],
  ['/docs/guides/frameworks/nuxt', '/docs/getting-started/nuxt', true],
  [
    '/docs/guides/providers/openai-functions',
    '/providers/ai-sdk-providers/openai',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/amazon-bedrock',
    '/providers/ai-sdk-providers/amazon-bedrock',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/anthropic',
    '/providers/ai-sdk-providers/anthropic',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/azure',
    '/providers/ai-sdk-providers/azure',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/fireworks',
    '/providers/ai-sdk-providers/fireworks',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/google-geneative-ai',
    '/providers/ai-sdk-providers/google',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/google-vertex',
    '/providers/ai-sdk-providers/google-vertex',
    true,
  ],
  [
    '/docs/providers/ai-sdk-providers/groq',
    '/providers/ai-sdk-providers/groq',
    true,
  ],
  [
    '/docs/providers/ai-sdk-provviders/groq',
    '/providers/ai-sdk-providers/groq',
    true,
  ],
  [
    '/docs/reference/stream-helpers/stream-data',
    '/docs/reference/ai-sdk-ui/stream-data#streamdata',
    true,
  ],
  [
    '/docs/reference/stream-helpers/to-data-stream-response',
    '/docs/reference/ai-sdk-core/stream-text#to-data-stream-response',
    true,
  ],
  [
    '/docs/troubleshooting/ai-sdk-errors',
    '/docs/reference/ai-sdk-errors',
    true,
  ],
  ['/docs/troubleshooting/common-issues', '/docs/troubleshooting', true],
  [
    '/docs/troubleshooting/common-issues/streaming-not-working-in-production',
    '/docs/troubleshooting/streaming-not-working-on-vercel',
    true,
  ],
  ['/docs/troubleshooting/migration-guide', '/docs/migration-guides', true],
  [
    '/providers/community-providers/custom-chat-settings',
    '/providers/community-providers/custom-providers',
    true,
  ],
  ['/providers/legacy-providers', '/docs/reference/stream-helpers', true],
  [
    '/providers/legacy-providers/anthropic',
    '/docs/reference/stream-helpers/anthropic-stream',
    true,
  ],
  [
    '/providers/legacy-providers/aws-bedrock',
    '/docs/reference/stream-helpers/aws-bedrock-stream',
    true,
  ],
  [
    '/providers/legacy-providers/azure-openai',
    '/docs/reference/stream-helpers',
    true,
  ],
  [
    '/providers/legacy-providers/cohere',
    '/docs/reference/stream-helpers/cohere-stream',
    true,
  ],
  [
    '/providers/legacy-providers/google',
    '/docs/reference/stream-helpers/google-generative-ai-stream',
    true,
  ],
  [
    '/providers/legacy-providers/inkeep',
    '/docs/reference/stream-helpers/inkeep-stream',
    true,
  ],
  [
    '/providers/legacy-providers/langchain',
    '/docs/reference/stream-helpers/langchain-stream',
    true,
  ],
  [
    '/providers/legacy-providers/mistral',
    '/docs/reference/stream-helpers/mistral-stream',
    true,
  ],
  [
    '/providers/legacy-providers/openai',
    '/docs/reference/stream-helpers/openai-stream',
    true,
  ],
  [
    '/providers/legacy-providers/openai-functions',
    '/providers/ai-sdk-providers/openai',
    true,
  ],
  ['/docs/guides/rag-chatbot-app', '/docs/guides/rag-chatbot', true],
  ['/docs/ai-sdk-rsc/actions', '/docs/ai-sdk-rsc/overview', true],
  [
    '/docs/reference/ai-sdk-core/middleware',
    '/docs/ai-sdk-core/middleware',
    true,
  ],
  [
    '/docs/lib/handle-messages',
    '/docs/ai-sdk-core/tools-and-tool-calling',
    true,
  ],
  ['/docs/guides/functions', '/docs/guides/rag-chatbot', true],
  [
    '/providers/ai-sdk-providers/openai-compatible',
    '/providers/openai-compatible-providers',
    true,
  ],
  [
    '/providers/legacy-providers/perplexity',
    '/docs/reference/stream-helpers',
    true,
  ],
  [
    '/providers/legacy-providers/replicate',
    '/docs/reference/stream-helpers/replicate-stream',
    true,
  ],
  ['/repo', 'https://github.com/vercel/ai', false],
  ['/rsc-demo', '/docs/ai-sdk-rsc/overview', true],
  ['/stream-data', '/docs/reference/ai-sdk-ui/stream-data', true],
  ['/demoXXXX', '/', true],
  ['/docs-og-image', '/', true],
  ['/providers/ai-sdk-providers/data/ai.pdf', '/', true],
  ['/repo/file.py', '/', true],
  ['/docs/ai-sdk-core/agents', '/docs/agents', true],
  ['/docs/announcing-ai-sdk-5-alpha', '/docs/announcing-ai-sdk-5-beta', true],
  ['/docs/announcing-ai-sdk-5-beta', 'https://vercel.com/blog/ai-sdk-5', true],
  ['/docs/harnesses/overview', '/docs/ai-sdk-harnesses/overview', true],
  [
    '/docs/reference/ai-sdk-ui/append-response-messages',
    '/docs/migration-guides/migration-guide-5-0#message-persistence-changes',
    true,
  ],
  [
    '/docs/reference/ai-sdk-ui/append-client-message',
    '/docs/migration-guides/migration-guide-5-0#message-persistence-changes',
    true,
  ],
  [
    '/docs/reference/ai-sdk-ui/pipe-data-stream-to-response',
    '/docs/reference/ai-sdk-ui/pipe-ui-message-stream-to-response',
    true,
  ],
  [
    '/docs/reference/ai-sdk-ui/stream-data',
    '/docs/migration-guides/migration-guide-5-0#stream-data-removal',
    true,
  ],
  [
    '/docs/ai-sdk-ui/smooth-stream-japanese',
    '/docs/reference/ai-sdk-core/smooth-stream',
    true,
  ],
  [
    '/docs/ai-sdk-ui/smooth-stream-chinese',
    '/docs/reference/ai-sdk-core/smooth-stream',
    true,
  ],
  [
    '/docs/reference/ai-sdk-ui/create-data-stream-response',
    '/docs/reference/ai-sdk-ui/create-ui-message-stream-response',
    true,
  ],
  [
    '/docs/reference/ai-sdk-ui/assistant-response',
    '/docs/reference/ai-sdk-ui/use-chat',
    true,
  ],
  ['/docs/foundations/agents', '/docs/agents/overview', true],
  [
    '/docs/reference/ai-sdk-errors/ai-no-audio-generated-error',
    '/docs/reference/ai-sdk-errors/ai-no-speech-generated-error',
    true,
  ],
  [
    '/docs/introduction/announcing-ai-sdk-6-beta',
    '/docs/announcing-ai-sdk-6-beta',
    true,
  ],
  ['/cookbook/guides/gemini-2-5', '/cookbook/guides/gemini', true],
  ['/docs/announcing-ai-sdk-6-beta', 'https://vercel.com/blog/ai-sdk-6', false],
] satisfies readonly LegacyRedirectTuple[];

export const legacyRedirects: LegacyRedirect[] = legacyRedirectData.map(
  ([source, destination, permanent]) => ({ source, destination, permanent }),
);
