import { OpenAICompatibleChatSettings } from '@ai-sdk/openai-compatible';

// https://docs.together.ai/docs/serverless-models#chat-models
export type TogetherAIChatModelId =
  | 'databricks/dbrx-instruct'
  | 'deepseek-ai/deepseek-llm-67b-chat'
  | 'google/gemma-2-27b-it'
  | 'google/gemma-2-9b-it'
  | 'google/gemma-2b-it'
  | 'Gryphe/MythoMax-L2-13b'
  | 'meta-llama/Llama-2-13b-chat-hf'
  | 'meta-llama/Llama-3-70b-chat-hf'
  | 'meta-llama/Llama-3-8b-chat-hf'
  | 'meta-llama/Llama-3.2-3B-Instruct-Turbo'
  | 'meta-llama/Meta-Llama-3-70B-Instruct-Lite'
  | 'meta-llama/Meta-Llama-3-70B-Instruct-Turbo'
  | 'meta-llama/Meta-Llama-3-8B-Instruct-Lite'
  | 'meta-llama/Meta-Llama-3-8B-Instruct-Turbo'
  | 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo'
  | 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'
  | 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'
  | 'microsoft/WizardLM-2-8x22B'
  | 'mistralai/Mistral-7B-Instruct-v0.1'
  | 'mistralai/Mistral-7B-Instruct-v0.2'
  | 'mistralai/Mistral-7B-Instruct-v0.3'
  | 'mistralai/Mixtral-8x22B-Instruct-v0.1'
  | 'mistralai/Mixtral-8x7B-Instruct-v0.1'
  | 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO'
  | 'nvidia/Llama-3.1-Nemotron-70B-Instruct-HF'
  | 'Qwen/Qwen2-72B-Instruct'
  | 'Qwen/Qwen2.5-72B-Instruct-Turbo'
  | 'Qwen/Qwen2.5-7B-Instruct-Turbo'
  | 'Qwen/Qwen2.5-Coder-32B-Instruct'
  | 'togethercomputer/StripedHyena-Nous-7B'
  | 'upstage/SOLAR-10.7B-Instruct-v1.0'
  | (string & {});

// https://docs.together.ai/docs/dedicated-models#chat-models
// export type TogetherAIChatModelId_Dedicated =
//   | 'databricks/dbrx-instruct'
//   | 'deepseek-ai/deepseek-coder-33b-instruct'
//   | 'deepseek-ai/deepseek-llm-67b-chat'
//   | 'google/gemma-2-27b-it'
//   | 'google/gemma-2-9b-it'
//   | 'google/gemma-2b-it'
//   | 'google/gemma-7b-it'
//   | 'gradientai/Llama-3-70B-Instruct-Gradient-1048k'
//   | 'Gryphe/MythoMax-L2-13b-Lite'
//   | 'Gryphe/MythoMax-L2-13b'
//   | 'Haotian Liu/LLaVa-Next (Mistral-7B)'
//   | 'HuggingFaceH4/zephyr-7b-beta'
//   | 'lmSys/Koala (13B)'
//   | 'lmSys/Koala-7B'
//   | 'lmSys/Vicuna v1.3 (13B)'
//   | 'lmSys/Vicuna v1.3 (7B)'
//   | 'lmSys/Vicuna v1.5 (13B)'
//   | 'lmSys/Vicuna v1.5 (7B)'
//   | 'lmSys/Vicuna v1.5 16K (13B)'
//   | 'Meta/Code Llama Instruct (13B)'
//   | 'Meta/Code Llama Instruct (13B)'
//   | 'Meta/Code Llama Instruct (34B)'
//   | 'Meta/Code Llama Instruct (34B)'
//   | 'Meta/Code Llama Instruct (70B)'
//   | 'Meta/Code Llama Instruct (7B)'
//   | 'Meta/LLaMA-2 Chat (13B)'
//   | 'Meta/LLaMA-2 Chat (13B)'
//   | 'Meta/LLaMA-2 Chat (70B)'
//   | 'Meta/LLaMA-2 Chat (7B)'
//   | 'Meta/LLaMA-2 Chat (7B)'
//   | 'Meta/Llama3 8B Chat HF INT4'
//   | 'Meta/Meta Llama 3 70B Instruct Lite'
//   | 'Meta/Meta Llama 3 70B Instruct Reference'
//   | 'Meta/Meta Llama 3 70B Instruct Turbo'
//   | 'Meta/Meta Llama 3 70B Instruct'
//   | 'Meta/Meta Llama 3 8B Instruct Lite'
//   | 'Meta/Meta Llama 3 8B Instruct Reference'
//   | 'Meta/Meta Llama 3 8B Instruct Turbo'
//   | 'Meta/Meta Llama 3 8B Instruct'
//   | 'Meta/Meta Llama 3.1 405B Instruct Turbo'
//   | 'Meta/Meta Llama 3.1 405B Instruct Turbo'
//   | 'Meta/Meta Llama 3.1 70B Instruct Turbo'
//   | 'Meta/Meta Llama 3.1 8B Instruct Turbo'
//   | 'Meta/Meta Llama 3.2 11B Vision Instruct Turbo'
//   | 'Meta/Meta Llama 3.2 3B Instruct Turbo'
//   | 'Meta/Meta Llama 3.2 90B Vision Instruct Turbo'
//   | 'Meta/Meta Llama Vision Free'
//   | 'Meta/Togethercomputer Llama3 8B Instruct Int8'
//   | 'microsoft/WizardLM-2-8x22B'
//   | 'mistralai/Mistral-7B-Instruct-v0.1'
//   | 'mistralai/Mistral-7B-Instruct-v0.2'
//   | 'mistralai/Mistral-7B-Instruct-v0.3'
//   | 'mistralai/Mixtral-8x22B-Instruct-v0.1'
//   | 'mistralai/Mixtral-8x7B-Instruct-v0.1'
//   | 'NousResearch/Hermes-2-Theta-Llama-3-70B'
//   | 'NousResearch/Nous-Capybara-7B-V1p9'
//   | 'NousResearch/Nous-Hermes-2-Mistral-7B-DPO'
//   | 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO'
//   | 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT'
//   | 'NousResearch/Nous-Hermes-Llama2-13b'
//   | 'NousResearch/Nous-Hermes-Llama2-70b'
//   | 'Open-Orca/Mistral-7B-OpenOrca'
//   | 'openchat/openchat-3.5-1210'
//   | 'Qwen/Qwen1.5-0.5B-Chat'
//   | 'Qwen/Qwen1.5-1.8B-Chat'
//   | 'Qwen/Qwen1.5-110B-Chat'
//   | 'Qwen/Qwen1.5-14B-Chat'
//   | 'Qwen/Qwen1.5-32B-Chat'
//   | 'Qwen/Qwen1.5-4B-Chat'
//   | 'Qwen/Qwen1.5-72B-Chat'
//   | 'Qwen/Qwen1.5-7B-Chat'
//   | 'Qwen/Qwen2-1.5B-Instruct'
//   | 'Qwen/Qwen2-72B-Instruct'
//   | 'Qwen/Qwen2-7B-Instruct'
//   | 'Qwen/Qwen2.5-72B-Instruct-Turbo'
//   | 'Qwen/Qwen2.5-7B-Instruct-Turbo'
//   | 'Qwen/Qwen2.5-Coder-32B-Instruct'
//   | 'snorkelai/Snorkel-Mistral-PairRM-DPO'
//   | 'Snowflake/snowflake-arctic-instruct'
//   | 'teknium/OpenHermes-2-Mistral-7B'
//   | 'teknium/OpenHermes-2p5-Mistral-7B'
//   | 'test/test11'
//   | 'togethercomputer/alpaca-7b'
//   | 'togethercomputer/guanaco-13b'
//   | 'togethercomputer/guanaco-33b'
//   | 'togethercomputer/guanaco-65b'
//   | 'togethercomputer/guanaco-7b'
//   | 'togethercomputer/SOLAR-10.7B-Instruct-v1.0-int4'
//   | 'togethercomputer/SOLAR-10.7B-Instruct-v1.0'
//   | 'Undi95/ReMM-SLERP-L2-13B'
//   | 'Undi95/Toppy-M-7B'
//   | 'WizardLM/WizardLM-13B-V1.2'
//   | (string & {});

export interface TogetherAIChatSettings extends OpenAICompatibleChatSettings {}
