import {
  DefaultGeneratedFile,
  type GeneratedFile,
} from '../generate-text/generated-file';

/**
 * An artifact generated by an artifact model.
 */
export interface GeneratedArtifact extends GeneratedFile {
  /**
   * Suggested filename supplied by the provider, when available.
   */
  readonly filename?: string;

  /**
   * Provider-independent hint describing the artifact's purpose.
   */
  readonly role?: string;
}

export class DefaultGeneratedArtifact
  extends DefaultGeneratedFile
  implements GeneratedArtifact
{
  readonly filename: string | undefined;
  readonly role: string | undefined;

  constructor(options: {
    data: string | Uint8Array;
    mediaType: string;
    filename?: string;
    role?: string;
  }) {
    super(options);
    this.filename = options.filename;
    this.role = options.role;
  }
}
