import { gateway } from 'ai';
import { run } from '../lib/run';

// Queries spend for traffic generated by the stream-text-with-tags example,
// combining multiple filters (model, tags, daily breakdown) in one call.
// Run stream-text-with-tags.ts first to generate matching data.

run(async () => {
  const today = new Date().toISOString().split('T')[0];
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split('T')[0];

  // Filter to the exact model and tags used by stream-text-with-tags.ts
  console.log(
    `\n--- Filtered spend: claude-haiku-4.5 + reporting-test tag (${thirtyDaysAgo} to ${today}) ---\n`,
  );

  const report = await gateway.getSpendReport({
    startDate: thirtyDaysAgo,
    endDate: today,
    datePart: 'day',
    model: 'anthropic/claude-haiku-4.5',
    tags: ['feature:reporting-test'],
  });

  if (report.results.length === 0) {
    console.log(
      'No results found.',
      'Run stream-text-with-tags.ts first, then wait a few minutes for data to appear.',
    );
    return;
  }

  for (const row of report.results) {
    console.log(
      [
        row.day,
        `$${row.totalCost.toFixed(4)} cost`,
        `${row.requestCount ?? 0} requests`,
        `${row.inputTokens ?? 0} in / ${row.outputTokens ?? 0} out tokens`,
      ].join(' | '),
    );
  }

  // Break down the same tagged traffic by provider to see routing
  console.log(`\n--- Same traffic grouped by provider ---\n`);

  const byProvider = await gateway.getSpendReport({
    startDate: thirtyDaysAgo,
    endDate: today,
    groupBy: 'provider',
    model: 'anthropic/claude-haiku-4.5',
    tags: ['feature:reporting-test'],
  });

  for (const row of byProvider.results) {
    console.log(
      `${row.provider}: $${row.totalCost.toFixed(4)} (${row.requestCount ?? 0} requests)`,
    );
  }
});
