// https://friendli.ai/models
export type FriendliAIChatModelId =
  | "meta-llama-3.1-8b-instruct"
  | "meta-llama-3.1-70b-instruct"
  | "mixtral-8x7b-instruct-v0-1"
  | "exaone-3.5-7.8b-instruct"
  | "exaone-3.5-32b-instruct"
  | (string & {});

export type FriendliAIBetaChatModelId =
  | "llama-3.2-11b-vision-instruct"
  | (string & {});

export interface FriendliAIChatSettings {
  /**
Modify the likelihood of specified tokens appearing in the completion.

Accepts a JSON object that maps tokens (specified by their token ID in
the GPT tokenizer) to an associated bias value from -100 to 100. You
can use this tokenizer tool to convert text to token IDs. Mathematically,
the bias is added to the logits generated by the model prior to sampling.
The exact effect will vary per model, but values between -1 and 1 should
decrease or increase likelihood of selection; values like -100 or 100
should result in a ban or exclusive selection of the relevant token.

As an example, you can pass {"50256": -100} to prevent the <|endoftext|>
token from being generated.
*/
  logitBias?: Record<number, number>;

  /**
Return the log probabilities of the tokens. Including logprobs will increase
the response size and can slow down response times. However, it can
be useful to better understand how the model is behaving.

Setting to true will return the log probabilities of the tokens that
were generated.

Setting to a number will return the log probabilities of the top n
tokens that were generated.
*/
  logprobs?: boolean | number;

  /**
Whether to enable parallel function calling during tool use. Default to true.
   */
  parallelToolCalls?: boolean;

  /**
Whether to use structured outputs. Defaults to false.

When enabled, tool calls and object generation will be strict and follow the provided schema.
 */
  structuredOutputs?: boolean;

  /**
   BETA FEATURE: Include the model's training loss in the response.
   */
  tools?: Array<
    | {
        type:
          | "web:url"
          | "web:search"
          | "math:calendar"
          | "math:statistics"
          | "math:calculator"
          | "code:python-interpreter";
      }
    | {
        type: "file:text";
        files: Array<string>;
      }
  >;

  /**
   BETA FEATURE: You can write a regular expression to force output that satisfies that regular expression.
   */
  regex?: string;

  /**
A unique identifier representing your end-user, which can help FriendliAI to
monitor and detect abuse. Learn more.
*/
  user?: string;
}
