import { experimental_generateVideo as generateVideo, gateway } from 'ai';
import { presentVideos } from '../../lib/present-video';
import { run } from '../../lib/run';
import { withSpinner } from '../../lib/spinner';

// FLUX 3 generates one video per call and takes a named resolution tier
// ('hd' or 'fhd') rather than pixel dimensions. Audio is generated by default,
// so `generateAudio` only has to be set to turn it off.
run(async () => {
  const { video, warnings } = await withSpinner(
    'Generating FLUX 3 video via AI Gateway...',
    () =>
      generateVideo({
        model: gateway.videoModel('bfl/flux-3-video'),
        prompt:
          'A white kitten chases a butterfly across a sunlit garden. Gentle ' +
          'camera tracking, natural movement, birdsong and rustling leaves.',
        aspectRatio: '16:9',
        duration: 8,
        poll: { timeoutMs: 600000 }, // 10 minutes
        providerOptions: {
          blackForestLabs: {
            resolution: 'fhd',
          },
        },
      }),
  );

  console.log('Warnings:', warnings);
  await presentVideos([video]);
});
