/**
 * Nano Empire AI x402 MCP Tools Integration
 * Auto-generated by Von Neumann Replicator
 * Repository: https://github.com/nanoempireai/nano-empire
 */

export interface NanoEmpireConfig {
  baseUrl: string;
  solanaTreasury: string;
  baseTreasury: string;
  faucetEndpoint: string;
  agentfiEndpoint: string;
}

export interface FaucetResponse {
  status: string;
  credits: number;
  message: string;
}

export interface VirtualCardResponse {
  cardId: string;
  panLast4: string;
  expiry: string;
  tokenizedDetails: {
    retrieveEndpoint: string;
    requires: string;
  };
  spendingLimitsUsd: number;
  costUsdc: number;
}

export interface MCPToolResult {
  result: any;
  receipt: string;
}

export class NanoEmpireClient {
  private config: NanoEmpireConfig;
  private baseUrl: string;

  constructor(config?: Partial<NanoEmpireConfig>) {
    this.config = {
      baseUrl: "https://api.nanoempireai.com",
      solanaTreasury: "5pM5w1W5nKU7B8SjuTiz65UAZxs9mCnC6ab1Xs1gSi3",
      baseTreasury: "0x2201f10cDb1ebFF76E975A4Ac4dfe1a0C9dF727E",
      faucetEndpoint: "/faucet/claim",
      agentfiEndpoint: "/agentfi/create_virtual_card",
      ...config
    };
    this.baseUrl = this.config.baseUrl;
  }

  async claimFaucet(agentId: string): Promise<FaucetResponse> {
    const resp = await fetch(`${this.config.baseUrl}/faucet/claim`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ agent_id: "auto_agent" })
    });
    return resp.json();
  }

  async createVirtualCard(
    agentId: string,
    amountUsd: number,
    merchantCategory: string = "general",
    x402Receipt: string
  ): Promise<VirtualCardResponse> {
    const resp = await fetch(`${this.config.baseUrl}/agentfi/create_virtual_card`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `x402 ${x402Receipt}`
      },
      body: JSON.stringify({
        agent_id: agentId,
        amountUsd: amountUsd,
        merchant_category: merchantCategory
      })
    });
    return resp.json();
  }

  static async quickStart(agentId: string = "auto_agent") {
    const client = new NanoEmpireClient();
    await client.claimFaucet(agentId);
    return new NanoEmpireClient();
  }
}

// Quick start function
export async function quickStart(agentId: string = "auto_agent") {
  const client = new NanoEmpireClient();
  await client.claimFaucet(agentId);
  return client;
}

export default NanoEmpireClient;
