import type { LanguageModelV4File } from '@ai-sdk/provider';
import {
  generateText,
  simulateReadableStream,
  streamText,
  ToolLoopAgent,
  type GeneratedFile,
} from 'ai';
import { MockLanguageModelV4 } from 'ai/test';

const sourceUrl = 'https://example.com/generated.png';
const expectedBytes = new TextEncoder().encode('generated-image-content');
const expectedBase64 = Buffer.from(expectedBytes).toString('base64');
const expectedDataUrl = `data:image/png;base64,${expectedBase64}`;

const usage = {
  inputTokens: { total: 1, noCache: 1, cacheRead: 0, cacheWrite: 0 },
  outputTokens: { total: 1, text: 1, reasoning: 0 },
};

function createFileData(
  data: LanguageModelV4File['data'],
): LanguageModelV4File {
  return {
    type: 'file',
    mediaType: 'image/png',
    data,
  };
}

function createModel(data: LanguageModelV4File['data']) {
  return new MockLanguageModelV4({
    doGenerate: {
      content: [createFileData(data)],
      finishReason: { unified: 'stop', raw: 'stop' },
      usage,
      warnings: [],
    },
    doStream: async () => ({
      stream: simulateReadableStream({
        chunks: [
          { type: 'stream-start', warnings: [] },
          createFileData(data),
          {
            type: 'finish',
            finishReason: { unified: 'stop', raw: 'stop' },
            usage,
          },
        ],
      }),
    }),
  });
}

function assertBytesEqual(
  actual: Uint8Array,
  expected: Uint8Array,
  label: string,
) {
  if (!Buffer.from(actual).equals(Buffer.from(expected))) {
    throw new Error(`${label}: generated bytes did not match the URL content`);
  }
}

function assertGeneratedFile(file: GeneratedFile, label: string) {
  const failures: string[] = [];

  if (file.base64 !== expectedBase64) {
    failures.push(
      `file.base64 contained ${JSON.stringify(file.base64)} instead of the fetched file content`,
    );
  }

  try {
    assertBytesEqual(file.uint8Array, expectedBytes, label);
  } catch (error) {
    failures.push(
      `reading file.uint8Array failed: ${
        error instanceof Error
          ? `${error.name}: ${error.message}`
          : String(error)
      }`,
    );
  }

  if (failures.length > 0) {
    throw new Error(`${label}: ${failures.join('; ')}`);
  }
}

async function assertUIFileUrl(
  stream: AsyncIterable<{ type: string; url?: string }>,
  label: string,
) {
  for await (const part of stream) {
    if (part.type !== 'file') {
      continue;
    }

    if (part.url !== sourceUrl && part.url !== expectedDataUrl) {
      throw new Error(
        `${label}: UI file URL was unusable: ${JSON.stringify(part.url)}`,
      );
    }
    return;
  }

  throw new Error(`${label}: UI stream did not contain a file part`);
}

async function checkUrlOutputs() {
  const failures: string[] = [];
  const check = async (label: string, run: () => Promise<void>) => {
    try {
      await run();
    } catch (error) {
      failures.push(
        `${label}: ${error instanceof Error ? `${error.name}: ${error.message}` : String(error)}`,
      );
    }
  };

  await check('generateText', async () => {
    const result = await generateText({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
      prompt: 'Return an image.',
    });
    assertGeneratedFile(result.files[0], 'generateText');
  });

  await check('streamText files', async () => {
    const result = streamText({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
      prompt: 'Return an image.',
    });
    assertGeneratedFile((await result.files)[0], 'streamText');
  });

  await check('streamText UI stream', async () => {
    const result = streamText({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
      prompt: 'Return an image.',
    });
    await assertUIFileUrl(result.toUIMessageStream(), 'streamText');
  });

  await check('ToolLoopAgent.generate', async () => {
    const agent = new ToolLoopAgent({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
    });
    const result = await agent.generate({ prompt: 'Return an image.' });
    assertGeneratedFile(result.files[0], 'ToolLoopAgent.generate');
  });

  await check('ToolLoopAgent.stream files', async () => {
    const agent = new ToolLoopAgent({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
    });
    const result = await agent.stream({ prompt: 'Return an image.' });
    assertGeneratedFile((await result.files)[0], 'ToolLoopAgent.stream');
  });

  await check('ToolLoopAgent.stream UI stream', async () => {
    const agent = new ToolLoopAgent({
      model: createModel({ type: 'url', url: new URL(sourceUrl) }),
    });
    const result = await agent.stream({ prompt: 'Return an image.' });
    await assertUIFileUrl(result.toUIMessageStream(), 'ToolLoopAgent.stream');
  });

  return failures;
}

async function checkInlineDataControls() {
  const base64Result = await generateText({
    model: createModel({ type: 'data', data: expectedBase64 }),
    prompt: 'Return an image.',
  });
  assertGeneratedFile(base64Result.files[0], 'base64 control');

  const byteResult = await generateText({
    model: createModel({ type: 'data', data: expectedBytes }),
    prompt: 'Return an image.',
  });
  assertGeneratedFile(byteResult.files[0], 'byte-array control');

  const streamResult = streamText({
    model: createModel({ type: 'data', data: expectedBase64 }),
    prompt: 'Return an image.',
  });
  await assertUIFileUrl(
    streamResult.toUIMessageStream(),
    'inline-data stream control',
  );
}

async function main() {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (input, init) => {
    const url =
      typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.toString()
          : input.url;

    if (url === sourceUrl) {
      return new Response(expectedBytes, {
        headers: { 'content-type': 'image/png' },
      });
    }

    return originalFetch(input, init);
  };

  try {
    await checkInlineDataControls();
    const failures = await checkUrlOutputs();

    if (failures.length > 0) {
      console.error(
        'ISSUE_20951: generated file URL outputs are not usable\n' +
          failures.map(failure => `- ${failure}`).join('\n'),
      );
      process.exitCode = 1;
      return;
    }

    console.log('Issue #20951 did not reproduce.');
  } finally {
    globalThis.fetch = originalFetch;
  }
}

main().catch(error => {
  console.error('REPRODUCTION_HARNESS_ERROR', error);
  process.exitCode = 2;
});
