import { OpenTelemetry } from '@ai-sdk/otel';
import type { LanguageModelV4 } from '@ai-sdk/provider';
import {
  BasicTracerProvider,
  InMemorySpanExporter,
  SimpleSpanProcessor,
} from '@opentelemetry/sdk-trace-node';
import {
  generateText,
  streamText,
  type LanguageModelCallEndEvent,
  type Telemetry,
} from 'ai';
import { convertArrayToReadableStream, MockLanguageModelV4 } from 'ai/test';

const primaryModelId = 'primary-model';
const fallbackModelId = 'fallback-model';
const fallbackInputTokens = 41;
const fallbackOutputTokens = 17;

const fallbackUsage = {
  inputTokens: {
    total: fallbackInputTokens,
    noCache: fallbackInputTokens,
    cacheRead: 0,
    cacheWrite: 0,
  },
  outputTokens: {
    total: fallbackOutputTokens,
    text: fallbackOutputTokens,
    reasoning: 0,
  },
};

function createFallbackWrapper(): LanguageModelV4 {
  const fallbackModel = new MockLanguageModelV4({
    provider: 'test-provider',
    modelId: fallbackModelId,
    doGenerate: {
      content: [{ type: 'text', text: 'generated by fallback' }],
      finishReason: { unified: 'stop', raw: 'stop' },
      usage: fallbackUsage,
      warnings: [],
      response: {
        id: 'fallback-generate-response',
        modelId: fallbackModelId,
        timestamp: new Date(0),
      },
    },
    doStream: {
      stream: convertArrayToReadableStream([
        {
          type: 'response-metadata',
          id: 'fallback-stream-response',
          modelId: fallbackModelId,
          timestamp: new Date(0),
        },
        { type: 'text-start', id: 'text-1' },
        {
          type: 'text-delta',
          id: 'text-1',
          delta: 'streamed by fallback',
        },
        { type: 'text-end', id: 'text-1' },
        {
          type: 'finish',
          finishReason: { unified: 'stop', raw: 'stop' },
          usage: fallbackUsage,
        },
      ]),
    },
  });

  return {
    specificationVersion: 'v4',
    provider: fallbackModel.provider,
    modelId: primaryModelId,
    supportedUrls: fallbackModel.supportedUrls,
    doGenerate: options => fallbackModel.doGenerate(options),
    doStream: options => fallbackModel.doStream(options),
  };
}

async function runScenario(kind: 'generateText' | 'streamText') {
  const exporter = new InMemorySpanExporter();
  const tracerProvider = new BasicTracerProvider({
    spanProcessors: [new SimpleSpanProcessor(exporter)],
  });
  const tracer = tracerProvider.getTracer(`issue-18229-${kind}`);

  let modelCallEndEvent: LanguageModelCallEndEvent | undefined;
  const eventRecorder: Telemetry = {
    onLanguageModelCallEnd(event) {
      modelCallEndEvent = event;
    },
  };
  const telemetry = {
    integrations: [new OpenTelemetry({ tracer }), eventRecorder],
  };

  let resultModelId: string;
  if (kind === 'generateText') {
    const result = await generateText({
      model: createFallbackWrapper(),
      prompt: 'Use the fallback.',
      telemetry,
    });
    resultModelId = result.response.modelId;
  } else {
    const result = streamText({
      model: createFallbackWrapper(),
      prompt: 'Use the fallback.',
      telemetry,
    });
    await result.text;
    resultModelId = (await result.response).modelId;
  }

  await tracerProvider.forceFlush();

  const inferenceSpan = exporter
    .getFinishedSpans()
    .find(span => span.name === `chat ${primaryModelId}`);

  if (inferenceSpan == null) {
    throw new Error(`${kind}: expected the language-model telemetry span`);
  }

  const attributes = inferenceSpan.attributes;
  const eventValues =
    modelCallEndEvent == null ? [] : Object.values(modelCallEndEvent);

  return {
    kind,
    resultModelId,
    eventModelId: modelCallEndEvent?.modelId,
    eventContainsFallbackModelId: eventValues.includes(fallbackModelId),
    requestModel: attributes['gen_ai.request.model'],
    responseModel: attributes['gen_ai.response.model'],
    inputTokens: attributes['gen_ai.usage.input_tokens'],
    outputTokens: attributes['gen_ai.usage.output_tokens'],
  };
}

async function main() {
  const observations = await Promise.all([
    runScenario('generateText'),
    runScenario('streamText'),
  ]);

  console.log(JSON.stringify(observations, null, 2));

  for (const observation of observations) {
    if (observation.resultModelId !== fallbackModelId) {
      throw new Error(
        `${observation.kind}: setup failed because result.response.modelId was not the fallback model`,
      );
    }
    if (
      observation.requestModel !== primaryModelId ||
      observation.inputTokens !== fallbackInputTokens ||
      observation.outputTokens !== fallbackOutputTokens
    ) {
      throw new Error(
        `${observation.kind}: setup failed because the telemetry span did not combine the primary request model with fallback usage`,
      );
    }
  }

  const affectedOperations = observations
    .filter(
      observation =>
        observation.responseModel !== fallbackModelId &&
        !observation.eventContainsFallbackModelId,
    )
    .map(observation => observation.kind);

  if (affectedOperations.length > 0) {
    throw new Error(
      `ISSUE #18229 REPRODUCED: gen_ai.response.model is missing for ${affectedOperations.join(
        ' and ',
      )} fallback calls`,
    );
  }
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
