export type GatewayVideoModelId =
  | 'alibaba/wan-v2.5-t2v-preview'
  | 'alibaba/wan-v2.6-i2v'
  | 'alibaba/wan-v2.6-i2v-flash'
  | 'alibaba/wan-v2.6-r2v'
  | 'alibaba/wan-v2.6-r2v-flash'
  | 'alibaba/wan-v2.6-t2v'
  | 'google/veo-3.0-fast-generate-001'
  | 'google/veo-3.0-generate-001'
  | 'google/veo-3.1-fast-generate-001'
  | 'google/veo-3.1-generate-001'
  | 'klingai/kling-v2.5-turbo-i2v'
  | 'klingai/kling-v2.5-turbo-t2v'
  | 'klingai/kling-v2.6-i2v'
  | 'klingai/kling-v2.6-t2v'
  | 'klingai/kling-v3.0-i2v'
  | 'klingai/kling-v3.0-t2v'
  | 'xai/grok-imagine-video'
  | (string & {});
