export type GatewaySpeechModelId =
  | 'fish-audio/s1'
  | 'fish-audio/s2-pro'
  | 'fish-audio/s2.1-pro'
  | 'google/gemini-3.8-flash-lite-tts'
  | 'google/gemini-3.8-flash-tts'
  | 'microsoft/mai-voice-2'
  | 'microsoft/mai-voice-2-flash'
  | 'microsoft/mai-voice-2.1'
  | 'microsoft/mai-voice-2.1-flash'
  | 'openai/tts-1'
  | 'openai/tts-1-hd'
  | 'spacexai/grok-tts'
  | 'minimax/speech-2.8-hd'
  | 'minimax/speech-2.8-turbo'
  | 'minimax/speech-2.6-hd'
  | 'minimax/speech-2.6-turbo'
  | 'minimax/speech-02-hd'
  | 'minimax/speech-02-turbo'
  | 'minimax/speech-01-hd'
  | 'minimax/speech-01-turbo'
  | (string & {});
