import { CodeBlock } from '@vercel/geistdocs/components/code-block';
import { geistShikiTheme } from '@vercel/geistdocs/shiki-theme';
import type { HighlighterCore as ShikiHighlighter } from 'shiki/core';

/**
 * Lazy module-level shiki singleton. Uses the fine-grained core API with
 * only the grammars the tools registry needs instead of the full `shiki`
 * bundle: importing the bundle puts all ~350 grammars into the compile
 * graph, which this app's build memory budget cannot afford (see the same
 * pattern in components/docs/interactive-code-preview.tsx).
 */
let highlighterPromise: Promise<ShikiHighlighter> | null = null;

const loadHighlighter = (): Promise<ShikiHighlighter> => {
  highlighterPromise ??= (async () => {
    const [{ createHighlighterCore }, { createJavaScriptRegexEngine }] =
      await Promise.all([
        import('shiki/core'),
        import('shiki/engine/javascript'),
      ]);
    return createHighlighterCore({
      engine: createJavaScriptRegexEngine(),
      langs: [
        import('@shikijs/langs/bash'),
        import('@shikijs/langs/typescript'),
      ],
      themes: [geistShikiTheme],
    });
  })();
  return highlighterPromise;
};

/**
 * Shiki-highlighted code inside the Geistdocs code block chrome, for code
 * that lives outside the MDX pipeline (such as the tools-registry usage
 * examples). Uses the same Geist theme as the MDX code blocks, so token
 * colors resolve through the shared `--shiki-token-*` variables.
 */
export const HighlightedCode = async ({
  code,
  lang,
}: {
  code: string;
  lang: 'bash' | 'typescript';
}) => {
  const highlighter = await loadHighlighter();
  const html = highlighter.codeToHtml(code, {
    lang,
    theme: geistShikiTheme,
  });

  // Keep only the highlighted line spans; the Geistdocs CodeBlock provides
  // its own <pre> wrapper.
  const codeTagStart = html.indexOf('<code');
  const contentStart = html.indexOf('>', codeTagStart) + 1;
  const contentEnd = html.lastIndexOf('</code>');
  const inner =
    codeTagStart === -1 || contentEnd === -1 || contentStart === 0
      ? null
      : html.slice(contentStart, contentEnd);

  if (inner === null) {
    return (
      <CodeBlock>
        <code className="[&_.line]:px-4">{code}</code>
      </CodeBlock>
    );
  }

  return (
    <CodeBlock>
      <code
        className="[&_.line]:px-4"
        // The markup is generated by shiki from registry code samples.
        dangerouslySetInnerHTML={{ __html: inner }}
      />
    </CodeBlock>
  );
};
