export type HuggingFaceChatModelId =
  | 'meta-llama/Llama-3.1-8B-Instruct'
  | 'meta-llama/Llama-3.1-70B-Instruct'
  | 'meta-llama/Llama-3.3-70B-Instruct'
  | 'deepseek-ai/DeepSeek-V3-0324'
  | 'deepseek-ai/DeepSeek-R1'
  | 'deepseek-ai/DeepSeek-R1-0528'
  | 'Qwen/Qwen3-235B-A22B-Instruct-2507'
  | 'Qwen/Qwen3-30B-A3B'
  | 'Qwen/Qwen2.5-7B-Instruct'
  | 'Qwen/Qwen2.5-VL-7B-Instruct'
  | 'google/gemini-2.5-pro-exp-03-25'
  | 'google/gemini-2.0-flash-thinking-exp'
  | 'google/gemini-2.0-flash-exp'
  | 'google/gemma-2-2b-it'
  | 'google/gemma-3-27b-it'
  | 'mistralai/Mistral-7B-Instruct-v0.3'
  | 'mistralai/Mixtral-8x7B-Instruct-v0.1'
  | 'nvidia/llama-3.1-nemotron-ultra-253b-v1'
  | (string & {});
