name: Auto-merge Release PRs

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable Auto-merge for Release PRs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Only run if PR is created by vercel-ai-sdk[bot] and branch starts with changeset-release/
    if: |
      github.event.pull_request.user.login == 'vercel-ai-sdk[bot]' &&
      startsWith(github.event.pull_request.head.ref, 'changeset-release/')
    
    steps:
      - name: Create access token for GitHub App
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.VERCEL_AI_SDK_GITHUB_APP_CLIENT_ID }}
          private-key: ${{ secrets.VERCEL_AI_SDK_GITHUB_APP_PRIVATE_KEY_PKCS8 }}

      - name: merge pull request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
